// One-click theme presets. Each sets the full palette + font + background
// style but deliberately leaves branding/content alone — applying a preset
// never touches eventTitle, showEventTitle, logo, or backgroundImage.
export const THEME_PRESETS = [
  {
    id: 'ocean',
    name: 'Ocean',
    theme: {
      primary: '#1e3d59',
      secondary: '#1c8c9a',
      accent: '#ff6f61',
      background: '#e0f7fa',
      surface: '#ffffff',
      textColor: null,
      headlineColor: null,
      winnerCardBg: null,
      winnerCardText: null,
      fontFamily: 'Poppins',
      backgroundStyle: 'waves',
    },
  },
  {
    id: 'sunset-carnival',
    name: 'Sunset Carnival',
    theme: {
      primary: '#7c2d5e',
      secondary: '#e85d2f',
      accent: '#ffc93c',
      background: '#fff1e0',
      surface: '#fffaf2',
      textColor: '#5a2145',
      headlineColor: '#e85d2f',
      winnerCardBg: '#fffaf2',
      winnerCardText: '#7c2d5e',
      fontFamily: 'Poppins',
      backgroundStyle: 'gradient',
      backgroundGradient: { from: '#ffd194', to: '#e85d2f', angle: 165 },
    },
  },
  {
    id: 'forest-raffle',
    name: 'Forest Raffle',
    theme: {
      primary: '#1f4d2e',
      secondary: '#4f8a5b',
      accent: '#d9a441',
      background: '#eef5e9',
      surface: '#ffffff',
      textColor: '#23402d',
      headlineColor: '#1f4d2e',
      winnerCardBg: '#ffffff',
      winnerCardText: '#1f4d2e',
      fontFamily: 'Georgia',
      backgroundStyle: 'solid',
    },
  },
  {
    id: 'midnight-gala',
    name: 'Midnight Gala',
    theme: {
      primary: '#e8e2f4',
      secondary: '#7a6bb5',
      accent: '#d4af37',
      background: '#171225',
      surface: '#262040',
      textColor: '#e8e2f4',
      headlineColor: '#d4af37',
      winnerCardBg: '#262040',
      winnerCardText: '#e8e2f4',
      fontFamily: 'Georgia',
      backgroundStyle: 'gradient',
      backgroundGradient: { from: '#171225', to: '#2e2154', angle: 160 },
    },
  },
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    theme: {
      primary: '#b83280',
      secondary: '#6bc5d2',
      accent: '#ff8fab',
      background: '#fdeff5',
      surface: '#ffffff',
      textColor: '#8a2360',
      headlineColor: '#b83280',
      winnerCardBg: '#ffffff',
      winnerCardText: '#b83280',
      fontFamily: 'Comic Sans MS',
      backgroundStyle: 'waves',
    },
  },
  {
    id: 'slate-corporate',
    name: 'Slate Corporate',
    theme: {
      primary: '#2d3a4a',
      secondary: '#5b7185',
      accent: '#3d8bfd',
      background: '#f2f5f8',
      surface: '#ffffff',
      textColor: '#2d3a4a',
      headlineColor: '#2d3a4a',
      winnerCardBg: '#ffffff',
      winnerCardText: '#2d3a4a',
      fontFamily: 'Inter',
      backgroundStyle: 'solid',
    },
  },
  {
    id: 'golden-ticket',
    name: 'Golden Ticket',
    theme: {
      primary: '#5c3a00',
      secondary: '#a87900',
      accent: '#e63946',
      background: '#fdf3d7',
      surface: '#fffbe8',
      textColor: '#5c3a00',
      headlineColor: '#a87900',
      winnerCardBg: '#fffbe8',
      winnerCardText: '#5c3a00',
      fontFamily: 'Georgia',
      backgroundStyle: 'gradient',
      backgroundGradient: { from: '#fdf3d7', to: '#f3c862', angle: 170 },
    },
  },
  {
    id: 'neon-arcade',
    name: 'Neon Arcade',
    theme: {
      primary: '#e6f7ff',
      secondary: '#00bcd4',
      accent: '#ff2e88',
      background: '#0d0d1f',
      surface: '#1c1c38',
      textColor: '#e6f7ff',
      headlineColor: '#ff2e88',
      winnerCardBg: '#1c1c38',
      winnerCardText: '#00e5ff',
      fontFamily: 'Courier New',
      backgroundStyle: 'gradient',
      backgroundGradient: { from: '#0d0d1f', to: '#241b4d', angle: 155 },
    },
  },
]
